name: "Create package"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  package:
    name: Create package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ./.node-version
      - run: yarn install
      - name: Create package
        run: yarn vscode:package
