name: "Publish"
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./.node-version
      - run: yarn install
      - name: Publish
        run: yarn vscode:publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Create package
        run: yarn vscode:package
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
