name: "Test"
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./.node-version
      - run: yarn install
      - run: xvfb-run -a yarn test
        if: runner.os == 'Linux'
      - run: yarn test
        if: runner.os != 'Linux'

  test-web:
    name: Test Web
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./.node-version
      - run: yarn install
      - run: xvfb-run -a yarn test-web
        if: runner.os == 'Linux'
      - run: yarn test-web
        if: runner.os != 'Linux'
